// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkfnxxmonjnxkomtbnra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rZm54eG1vbmpueGtvbXRibnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzExMTIsImV4cCI6MjA2MzQwNzExMn0.fdvzu1nD5x3-LzEMqWXkFN8Yp3n2eR9P2VsCmKFocys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);